server.port=8080
spring.data.mongodb.database=GPlankEquityTesting
spring.application.name=equity_transaction_service
spring.data.mongodb.uri=mongodb+srv://devcluster:devcluster@devcluster.yfxmlld.mongodb.net/GplanckEquityTesting